### ISSUE TITLE
Provide Kieker-instrumented docker images

### ISSUE THREAD

**Issue by joakimkistowski** [DescartesResearch/Pet-Supply-Store#33] opened 2017-09-08 08:50 UTC

**Comment by SimonEismann** [comment] 2017-09-13 14:17
Should work now, definitly should be tested atleast once though

**Comment by joakimkistowski** [comment] 2017-10-26 14:48
Builds are still failing at the moment.

**Comment by SimonEismann** [comment] 2017-10-27 10:28
It seems this build broke it:
https://github.com/DescartesResearch/Pet-Supply-Store/commit/6b013b411cad9dc74c22412bcc16d3872265039e

Message:
Caused by: com.spotify.docker.client.exceptions.DockerException: The command '/bin/sh -c mkdir -p /opt/kieker/agent &&   mkdir -p /opt/kieker/logs &&   wget -q "${KIEKER_AGENT_JAR_SRC}" -O "/opt/kieker/agent/agent.jar" &&   ln -s /usr/local/tomcat/webapps /opt/kieker/webapps &&   sed -i '250i\'"export KIEKER_JAVA_OPTS=\"     -javaagent:/opt/kieker/agent/agent.jar     -Dkieker.monitoring.configuration=/opt/kieker/config/kieker.monitoring.properties     -Dkieker.monitoring.writer.filesystem.AsciiFileWriter.customStoragePath=/opt/kieker/logs     -Daj.weaving.verbose=true     -Dkieker.monitoring.skipDefaultAOPConfiguration=true     \"" /usr/local/tomcat/bin/catalina.sh &&   sed -i '251i\'"export JAVA_OPTS=\"\${KIEKER_JAVA_OPTS} \${JAVA_OPTS}\"" /usr/local/tomcat/bin/catalina.sh' returned a non-zero code: 8

**Comment by SimonEismann** [comment] 2017-10-27 12:50
Kieker updated from 1.13 to 1.14 which broke the pull, fixed now

**Closed by SimonEismann** 2017-10-27 12:50 UTC
Labels: enhancement
